//
// Created by alex on 5/2/18.
//

#ifndef HW5_MULTI_LOOKUP_H
#define HW5_MULTI_LOOKUP_H

#include <arpa/inet.h>
#define MAX_INPUT_FILES 10

#define MAX_NAME_LENGTH 1025
#define MAX_IP_LENGTH INET_ADDRSTRLEN
enum ERROR {INCORRECT_PARAMS_AMOUNT=128,FEW_FILES_TO_PROCESS,OUTPUT_FILE_NOT_EXISTS,IMPORT_FILE_READ_ERROR,PTHREAD_CREATE_ERROR,PTHREAD_JOIN_ERROR};



#endif //HW5_MULTI_LOOKUP_H
